CREATE TABLE STUDENT(
	id INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	STUDY_YEAR INTEGER NOT NULL,
	SECTION VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE PROFESSOR(
	id INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE COURSE(
	id INTEGER NOT NULL AUTO_INCREMENT,
	COURSE_NAME VARCHAR(255) NOT NULL,
	CREDITS INTEGER NOT NULL,
	PROFESSOR_ID INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE EXAM(
	id INTEGER NOT NULL AUTO_INCREMENT,
	ACADEMIC_YEAR VARCHAR(255) NOT NULL,
	SESSION_TYPE VARCHAR(255) NOT NULL,
	STUDY_YEAR INTEGER NOT NULL,
	SECTION VARCHAR(255) NOT NULL,
	COURSE_ID INTEGER NOT NULL,
	PROFESSOR_ID INTEGER NOT NULL,
	STUDENT_ID INTEGER NOT NULL,
	PRIMARY KEY(id)
);